confronto: Esercizio_confronto.o alg1_variants.o
	gcc -o confronto Esercizio_confronto.c alg1_variants.c -Wall -ansi -pedantic
Esercizio2_confronto.o: Esercizio_confronto.c
	gcc -c Esercizio_confronto.c -Wall -ansi -pedantic
alg1_variants.o: alg1_variants.c
	gcc -c alg1_variants.c -Wall -ansi -pedantic	
		
